const defaultCategories = [
  // Income categories
  {
    name: "Salary",
    type: "income",
    color: "#4CAF50",
    icon: "payments",
    isDefault: true,
  },
  {
    name: "Business",
    type: "income",
    color: "#2196F3",
    icon: "business",
    isDefault: true,
  },
  {
    name: "Investments",
    type: "income",
    color: "#9C27B0",
    icon: "trending_up",
    isDefault: true,
  },
  {
    name: "Gifts",
    type: "income",
    color: "#E91E63",
    icon: "card_giftcard",
    isDefault: true,
  },
  {
    name: "Other Income",
    type: "income",
    color: "#FF9800",
    icon: "account_balance",
    isDefault: true,
  },

  // Expense categories
  {
    name: "Food & Dining",
    type: "expense",
    color: "#FF5722",
    icon: "restaurant",
    isDefault: true,
  },
  {
    name: "Groceries",
    type: "expense",
    color: "#8BC34A",
    icon: "shopping_cart",
    isDefault: true,
  },
  {
    name: "Transportation",
    type: "expense",
    color: "#3F51B5",
    icon: "directions_car",
    isDefault: true,
  },
  {
    name: "Rent/Mortgage",
    type: "expense",
    color: "#795548",
    icon: "home",
    isDefault: true,
  },
  {
    name: "Utilities",
    type: "expense",
    color: "#607D8B",
    icon: "power",
    isDefault: true,
  },
  {
    name: "Phone",
    type: "expense",
    color: "#00BCD4",
    icon: "phone_android",
    isDefault: true,
  },
  {
    name: "Entertainment",
    type: "expense",
    color: "#673AB7",
    icon: "movie",
    isDefault: true,
  },
  {
    name: "Shopping",
    type: "expense",
    color: "#FFC107",
    icon: "shopping_bag",
    isDefault: true,
  },
  {
    name: "Health & Medical",
    type: "expense",
    color: "#F44336",
    icon: "local_hospital",
    isDefault: true,
  },
  {
    name: "Personal Care",
    type: "expense",
    color: "#E91E63",
    icon: "spa",
    isDefault: true,
  },
  {
    name: "Education",
    type: "expense",
    color: "#009688",
    icon: "school",
    isDefault: true,
  },
  {
    name: "Travel",
    type: "expense",
    color: "#CDDC39",
    icon: "flight",
    isDefault: true,
  },
  {
    name: "Gifts & Donations",
    type: "expense",
    color: "#9C27B0",
    icon: "redeem",
    isDefault: true,
  },
  {
    name: "Other Expenses",
    type: "expense",
    color: "#9E9E9E",
    icon: "more_horiz",
    isDefault: true,
  },
];

module.exports = defaultCategories;
